from __future__ import annotations
import os as _os, sys as _sys
_sys.path.insert(0, _os.path.join(_os.path.dirname(_os.path.abspath(__file__)), "..", "src"))
_sys.path.insert(0, _os.path.dirname(_os.path.abspath(__file__)))
import config
"""
start_persistence.py — does a start predict the NEXT start, and does a streak add more?
=======================================================================================
Two different questions live inside "how much does starting last week matter":

  Q1  LAG-1 STATE DEPENDENCE.  P(start | started last match) vs P(start | did not).
      The naive between-player contrast is almost entirely FRAILTY: nailed-on players
      supply nearly all the 1->1 transitions and fringe players nearly all the 0->0
      ones, so the gap measures who the players are, not what last week did. The
      within-player-season contrast (a fixed-effects estimator: each player is his own
      control) is the identified quantity.

  Q2  DURATION DEPENDENCE.  Does h(k) = P(start at t+1 | k consecutive starts through t)
      keep rising in k? Raw h(k) rises under a pure mover-stayer process with ZERO true
      duration dependence, because a long streak is a filter that selects high-p players.
      The null is therefore NOT h(k) = const. It is the streak profile generated by each
      player's OWN start rate with the ordering destroyed.

NULL — a within-player-season permutation of the outcome sequence. It preserves each
player-season's start COUNT exactly (so all frailty survives) and destroys only the
order. Excess = h_obs(k) - h_perm(k) is the part of the streak profile that ordering
buys. Following the project's permutation guard, the OUTCOME is permuted, not labels.

CONFOUND, stated up front: h_obs - h_perm bundles two channels that this data cannot
separate — (a) selection state dependence (a manager keeps a settled XI) and (b)
availability persistence (a fit player stays fit; an injury is a BLOCK of zeros, and
clustered zeros mechanically cluster the ones too). Both are real for forecasting; only
(a) is "trust". The `nogap` scope re-runs on player-seasons with no absence block of
GAP+ consecutive non-appearances, which strips most injury spells.

DEFINITIONS
  unit          one player-season match sequence, ordered by kickoff_time (so a double
                gameweek is two ordered matches, not one)
  start         native `starts` column (2022/23 on). The mins>=60 proxy needed for
                earlier seasons spuriously BREAKS streaks whenever a starter is hooked
                before the hour, so it is reported as a separate scope, not pooled in.
  streak k      run length of consecutive starts ending at match t, reset each season
  outcome       is_start at match t+1 of the same season
  censoring     the last match of each sequence has no successor and is dropped. A
                January exit out of the league is INFORMATIVE censoring (losing your
                place precedes the transfer), which biases h upward slightly at low k.

CIs are a cluster bootstrap over player_code (a player's matches are not independent).

Run:  python studies/start_persistence.py
"""
import warnings; warnings.filterwarnings("ignore")
import numpy as np, pandas as pd
import fpl_history as fh

NATIVE = ("2022-23", "2023-24", "2024-25", "2025-26")   # native `starts` column
PROXY = ("2016-17", "2017-18", "2018-19", "2019-20", "2020-21", "2021-22")
KS = (1, 2, 3, 4, 5, 6, 8, 10, 15, 20, 25)
KMAX = 30
N_BOOT = 300
N_PERM = 200
GAP = 4            # a run of >=GAP consecutive non-appearances counts as an absence
MIN_CELL = 30      # do not report a hazard cell thinner than this
OUT = _os.path.join(_os.path.dirname(_os.path.abspath(__file__)), "start_persistence.csv")
rng = np.random.default_rng(20260906)


# ---------------------------------------------------------------- data
def _season_seq(season):
    """One row per player-match, ordered, keeping kickoff_time (fh's keep list drops it)."""
    path = _os.path.join(config.history(season), "gws", "merged_gw.csv")
    d = fh._read_csv(path)
    code, _ = fh._id_to_code(season)
    d["player_code"] = d["element"].map(code)
    rate = d["player_code"].notna().mean()
    if rate < fh.MIN_MATCH_RATE:
        raise RuntimeError(f"{season}: only {rate:.1%} of rows resolved to a player_code")
    d = d[d["player_code"].notna()].copy()
    d["player_code"] = d["player_code"].astype(int)
    d["mins"] = pd.to_numeric(d.get("minutes"), errors="coerce").fillna(0.0)
    if "starts" in d.columns:
        d["is_start"] = (pd.to_numeric(d["starts"], errors="coerce").fillna(0) > 0)
        native = True
    else:
        d["is_start"] = d["mins"] >= fh.START_MINUTES
        native = False
    d["ko"] = pd.to_datetime(d.get("kickoff_time"), errors="coerce", utc=True)
    d["gw"] = pd.to_numeric(d.get("GW", d.get("round")), errors="coerce")
    if "fixture" in d.columns:
        d = d.drop_duplicates(subset=["player_code", "fixture"])
    d["season"] = season
    d["native"] = native
    return d[["player_code", "season", "gw", "ko", "mins", "is_start", "native"]]


def build(seasons):
    p = pd.concat([_season_seq(s) for s in seasons], ignore_index=True)
    return p.sort_values(["player_code", "season", "ko", "gw"],
                         kind="mergesort").reset_index(drop=True)


def _runs(v):
    """Run length of the CURRENT value, ending at each position."""
    out = np.empty(len(v), dtype=np.int32)
    r, prev = 0, None
    for i, x in enumerate(v):
        r = r + 1 if (prev is not None and x == prev) else 1
        out[i] = r
        prev = x
    return out


def sequences(panel):
    seqs = []
    for (pc, _s), g in panel.groupby(["player_code", "season"], sort=False):
        v = g["is_start"].to_numpy().astype(np.int8)
        if len(v) < 2:
            continue
        seqs.append((int(pc), v, g["mins"].to_numpy()))
    return seqs


def has_absence(mins, gap=GAP):
    z = (mins <= 0).astype(np.int8)
    r = _runs(z)
    return bool(((z == 1) & (r >= gap)).any())


# ---------------------------------------------------------------- estimators
def flatten(seqs):
    """All sequences end to end, plus the segment id each position belongs to.

    Everything below works on this flat form. The estimators are unchanged — the loop
    version is `_runs` above and is kept for the per-sequence work — but the null needs
    N_PERM + N_BOOT full passes over ~113k player-matches, and a Python inner loop there
    costs minutes per scope inside `test_all`.
    """
    lens = [len(s[1]) for s in seqs]
    v = np.concatenate([s[1] for s in seqs]).astype(np.int8)
    seg = np.repeat(np.arange(len(seqs)), lens)
    return v, seg


def _runs_flat(v, seg):
    """Run length of the current value ending at each position, reset at segment starts."""
    n = len(v)
    idx = np.arange(n)
    new = np.empty(n, dtype=bool)
    new[0] = True
    new[1:] = (v[1:] != v[:-1]) | (seg[1:] != seg[:-1])
    return idx - np.maximum.accumulate(np.where(new, idx, 0)) + 1


def profile_flat(v, seg, kmax=KMAX):
    """Numerator/denominator by exact streak length for both states.
    Index k holds streaks of exactly k; index kmax is the >=kmax accumulator."""
    n = len(v)
    r = np.minimum(_runs_flat(v, seg), kmax)
    valid = np.empty(n, dtype=bool)                  # has a successor in the SAME season
    valid[:-1] = seg[1:] == seg[:-1]
    valid[-1] = False
    ynext = np.zeros(n, dtype=float)
    ynext[:-1] = v[1:]
    m1 = valid & (v == 1)
    m0 = valid & (v == 0)
    bc = lambda m, w: np.bincount(r[m], weights=w, minlength=kmax + 1)[:kmax + 1]
    return bc(m1, ynext[m1]), bc(m1, None), bc(m0, ynext[m0]), bc(m0, None)


def profile(seqs, kmax=KMAX):
    return profile_flat(*flatten(seqs), kmax)


def _h(num, den):
    with np.errstate(invalid="ignore", divide="ignore"):
        return np.where(den > 0, num / den, np.nan)


def within_player_lag1(seqs, min_each=5):
    """Fixed-effects lag-1 contrast, computed WITHIN each player-season:
    P(start_{t+1}|start_t) - P(start_{t+1}|no start_t). Frailty differences out."""
    diffs, w = [], []
    for _pc, v, _m in seqs:
        a, b = v[:-1], v[1:]
        n1, n0 = int((a == 1).sum()), int((a == 0).sum())
        if n1 < min_each or n0 < min_each:
            continue
        diffs.append(float(b[a == 1].mean() - b[a == 0].mean()))
        w.append(min(n1, n0))
    return np.array(diffs), np.array(w, dtype=float)


def permute_flat(v, seg):
    """Shuffle WITHIN each player-season. `seg` is already sorted and contiguous, so a
    lexsort keyed (random, segment) reorders inside segments and never across them."""
    return v[np.lexsort((rng.random(len(v)), seg))]


def boot_ci(seqs, n=N_BOOT, kmax=KMAX):
    """Cluster bootstrap over player_code on the observed start-hazard profile.

    Resampling the PLAYER, not the match: a player's matches are not independent, and a
    naive match-level bootstrap would understate the CI by exactly that dependence.
    """
    by_pc = {}
    for s in seqs:
        by_pc.setdefault(s[0], []).append(s[1])
    codes = np.array(list(by_pc.keys()))
    vals = np.full((n, kmax + 1), np.nan)
    for i in range(n):
        pick = rng.choice(codes, size=len(codes), replace=True)
        arrs = [a for c in pick for a in by_pc[c]]
        v = np.concatenate(arrs).astype(np.int8)
        seg = np.repeat(np.arange(len(arrs)), [len(a) for a in arrs])
        ns, ds, _a, _b = profile_flat(v, seg, kmax)
        vals[i] = _h(ns, ds)
    return np.nanpercentile(vals, 2.5, axis=0), np.nanpercentile(vals, 97.5, axis=0)


# ---------------------------------------------------------------- report
def run_scope(seqs, label, rows):
    v, seg = flatten(seqs)
    ns, ds, nn, dn = profile_flat(v, seg)
    h, hn = _h(ns, ds), _h(nn, dn)

    perm = np.full((N_PERM, KMAX + 1), np.nan)
    for i in range(N_PERM):
        pns, pds, _a, _b = profile_flat(permute_flat(v, seg), seg)
        perm[i] = _h(pns, pds)
    lo, hi = boot_ci(seqs)

    base = float(np.concatenate([v for _p, v, _m in seqs]).mean())
    print(f"  {'k':>3} {'n':>7} {'h_obs':>7} {'95% CI':>15} {'h_null':>7} "
          f"{'excess':>7} {'z':>6}")
    for k in KS:
        if k > KMAX or ds[k] < MIN_CELL:
            continue
        pm, ps = np.nanmean(perm[:, k]), np.nanstd(perm[:, k])
        z = (h[k] - pm) / ps if ps > 0 else np.nan
        rows.append(dict(scope=label, state="start", k=k, n=int(ds[k]), h_obs=h[k],
                         lo=lo[k], hi=hi[k], h_null=pm, null_sd=ps,
                         excess=h[k] - pm, z=z, base_rate=base))
        print(f"  {k:>3} {int(ds[k]):>7} {h[k]:>7.3f} "
              f"{'[%.3f,%.3f]' % (lo[k], hi[k]):>15} {pm:>7.3f} "
              f"{h[k] - pm:>+7.3f} {z:>6.1f}")

    print(f"  {'-- non-start streaks: P(start next | k consecutive non-starts)':<50}")
    for k in KS:
        if k > KMAX or dn[k] < MIN_CELL:
            continue
        rows.append(dict(scope=label, state="nonstart", k=k, n=int(dn[k]), h_obs=hn[k],
                         lo=np.nan, hi=np.nan, h_null=np.nan, null_sd=np.nan,
                         excess=np.nan, z=np.nan, base_rate=base))
        print(f"  {k:>3} {int(dn[k]):>7} {hn[k]:>7.3f}")


def main():
    rows = []
    print("\n=== loading ===")
    nat = sequences(build(NATIVE))
    print(f"native : {len(nat):5d} player-seasons, "
          f"{sum(len(v) for _p, v, _m in nat):6d} player-matches, "
          f"{len(set(p for p, _v, _m in nat)):4d} players  ({'/'.join(NATIVE)})")
    nogap = [s for s in nat if not has_absence(s[2])]
    print(f"nogap  : {len(nogap):5d} player-seasons "
          f"(no {GAP}+ consecutive non-appearance block)")
    prox = sequences(build(PROXY))
    print(f"proxy  : {len(prox):5d} player-seasons, mins>=60 definition "
          f"({'/'.join(PROXY)})")

    print("\n=== Q1  lag-1 state dependence: pooled vs within-player ===")
    for label, sq in (("native", nat), ("nogap", nogap), ("proxy", prox)):
        a = np.concatenate([v[:-1] for _p, v, _m in sq])
        b = np.concatenate([v[1:] for _p, v, _m in sq])
        p11, p01 = b[a == 1].mean(), b[a == 0].mean()
        d, w = within_player_lag1(sq)
        wm = float(np.average(d, weights=w)) if len(d) else np.nan
        dlo, dhi = (np.nanpercentile(d, [2.5, 97.5]) if len(d) else (np.nan, np.nan))
        print(f"  {label:7s} P(S|S)={p11:.3f}  P(S|not S)={p01:.3f}  "
              f"pooled gap={p11 - p01:+.3f}  ||  WITHIN-player gap={wm:+.3f}  "
              f"(n={len(d)} player-seasons, spread {dlo:+.3f}..{dhi:+.3f})")
        rows.append(dict(scope=label, state="lag1", k=1, n=int(len(a)), h_obs=p11,
                         lo=np.nan, hi=np.nan, h_null=p01, null_sd=np.nan,
                         excess=wm, z=np.nan, base_rate=float(a.mean())))

    print("\n=== Q2  duration dependence vs the frailty-preserving permutation null ===")
    for label, sq in (("native", nat), ("nogap", nogap), ("proxy", prox)):
        print(f"\n  --- {label} ---")
        run_scope(sq, label, rows)

    pd.DataFrame(rows).to_csv(OUT, index=False)
    print(f"\nwrote {OUT}")


if __name__ == "__main__":
    main()
